### ISSUE TITLE
注册问题

### ISSUE THREAD

**Issue by l1aovo** [qinggan/phpok#14]
![image](https://user-images.githubusercontent.com/75210196/225851732-22255796-75c1-421f-a54f-970b1a7570e3.png)
![image](https://user-images.githubusercontent.com/75210196/225851801-92cbb24d-8510-417b-bcf1-493193b02f5e.png)
![image](https://user-images.githubusercontent.com/75210196/225851865-0c3d38c2-e116-4b6a-ba73-3b06aeda74e0.png)
普通用户注册 ，爆禁用函数user函数
```
POST /api.php?c=register&f=save HTTP/1.1


group_id=2&_login=1&_back=http%3A%2F%2F172.21.28.13%3A41080%2F&user=L1ao&_vcode=U2343303&newpass=L1aoL1aoL1ao&chkpass=L1aoL1aoL1ao&mobile=110&email=110%40qq.com&is_ok=on
```

**Comment by qinggan** [comment]
收到，BUG。经测试该禁用方法冲突较多！我已暂停掉了！后天就更新版本

**Comment by qinggan** [comment]
程序已经升级修正，请更新
Updated, please upgrade in the background
